export_plots: true

disable_version_detection: true

# Run only these modules
run_modules:
  - riker
  - bcftools

module_order:
  - riker:
      name: "Riker (Cram quality)"
  - bcftools:
      name: "Bcftools"

table_sample_merge:
  "R1": "_R1"
  "R2": "_R2"

fn_clean_exts:
  - ".markdup.json"
  - ".stats.txt"
  - ".coverage"
  - ".bam"
  - ".cram"
  - ".F"
  - ".flagstats.txt"
  - ".vcf.gz"
